const ACTIONS = {
  CHANGE_NAME: 'CHANGE_NAME',
  CHANGE_PERSON: 'CHANGE_PERSON',
  CHANGE_DIRECTION: 'CHANGE_DIRECTION'
}

const MUTATIONS = {
  CHANGE_NAME: 'CHANGE_NAME',
  CHANGE_PERSON: 'CHANGE_PERSON',
  CHANGE_DIRECTION: 'CHANGE_DIRECTION'
}

export {
  ACTIONS,
  MUTATIONS
};
